database:
  user: ""
  url: ""
  pass: ""

npc-settings:
  world: "world" # The world that all npcs spawn in.
  skull-merchants: # Where the Skull Merchant npc spawns. 4 available npcs, add more in the Source Code
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

  soul-traders: # Where the Soul Traders npc spawns. 4 available npcs, add more in the Source Code
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

  whispering-dealers: # Where the Whispering Dealers npc spawns. 4 available npcs, add more in the Source Code
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

loot-table:
  loot1: # Set this Mythic Mob Type (use - for spaces)
    coins: 0 # How many coins will the player get?
    silver: 0
    xp: 0 # How many xp will the player get for set company
    company: "" # st, sm, wd
  loot2:
    coins: 0
    silver: 0
    xp: 0
    company: ""

islands:
  island1:
    name: ""
    x: 0
    y: 0
    z: 0