name: SeaX
version: '${project.version}'
main: me.karlito.seax.SeaX
api-version: '1.19'

# This sets PlaceholderAPI as an optional dependency for your plugin.
softdepend: [PlaceholderAPI]

commands:
  IronAxe:
    description: Give players Ender Bow.
  dash:
    description: Push you forward.
  testgui:
    description: Test api with itemsadder.
  defGui:
    description: Test api with itemsadder but wraps the def. inventory.
  mongo:
    description: Levels.