world: "world"

database:
  user: ""
  url: ""
  pass: ""

npc-settings:
  world: "world" # The world that all npcs spawn in.
  skull-merchants: # Where the Skull Merchant npc spawns.
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

  soul-traders:
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

  whispering-dealers:
    cords1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0
    cords4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0

loot-table:
  loot1: # Set this Mythic Mob Type (use - for spaces)
    coins: 0 # How many coins will the player get?
    silver: 0
    xp: 0 # How many xp will the player get for set company
    company: "" # st, sm, wd
    voyageLevel: 1 # In what voyages will the loot spawn 0 - 5. 0 = World Event
  loot2:
    coins: 0
    silver: 0
    xp: 0
    company: ""
    voyageLevel: 1

islands:
  island1:
    name: "Island 1"
    x: 0.0  # Values for the compass
    y: 0.0
    z: 0.0
    voyageLevel: 1
    voyageLootSpot: # Set the proximity where the voyage loot will spawn
      x: 0.0
      y: 0.0
      z: 0.0
  island2:
    name: "Island 2"
    x: 0.0
    y: 0.0
    z: 0.0
    voyageLevel: 1
    voyageLootSpot:
      x: 0.0
      y: 0.0
      z: 0.0

safezones:
  safezone1:
    name: "safeZone Name"
    min-x: 0.0
    min-y: 0.0
    min-z: 0.0
    max-x: 0.0
    max-y: 0.0
    max-z: 0.0

mobs:
  zombie: # Set this Mythic Mob Type
    voyageLevel: 1  # In what voyages will the mob spawn 0 = WORLD EVENT

stores:
  sm:
    mysword:
      gui_index: 0
      id: 1
      price:
        coins: 500
        silver: 100
  st:
  wd:

voyages:
  voyage1:
    level: 1
    name: "The Great Voyage"
    costSilver: 0
    costCoins: 100