name: SeaX
version: '0.1'
main: me.karlito.seax.SeaX
api-version: '1.19'

# This sets PlaceholderAPI as an optional dependency for your plugin.
softdepend: [PlaceholderAPI]
depend: [Citizens, TitleAPI]

commands:
  IronAxe:
    description: Give players Ender Bow.
  dash:
    description: Push you forward.
  testgui:
    description: Test api with itemsadder.
  crew:
    description: Crew Create Invite